CREATE TABLE BLOOD_BANK (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(150),
    contact_no VARCHAR2(15) UNIQUE,
    email VARCHAR2(100) UNIQUE
);

CREATE TABLE DONOR (
    donor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    age NUMBER CHECK (age BETWEEN 18 AND 65),
    gender VARCHAR2(10) CHECK (gender IN ('Male','Female','Other')),
    blood_group VARCHAR2(5) NOT NULL,
    phone VARCHAR2(15) UNIQUE,
    email VARCHAR2(100),
    address VARCHAR2(200),
    last_donation_date DATE
);

CREATE TABLE USER_ADMIN (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('Admin','Staff')),
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE HOSPITAL (
    hospital_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_name VARCHAR2(150) NOT NULL,
    address VARCHAR2(200),
    contact_no VARCHAR2(15) UNIQUE,
    email VARCHAR2(100)
);

CREATE TABLE BLOOD_UNIT (
    unit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_group VARCHAR2(5) NOT NULL,
    collection_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    status VARCHAR2(20) 
        CHECK (status IN ('Available','Issued','Expired')),
    bank_id NUMBER,
    
    CONSTRAINT fk_unit_bank
    FOREIGN KEY (bank_id)
    REFERENCES BLOOD_BANK(bank_id)
);

CREATE TABLE DONATION_RECORD (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id NUMBER NOT NULL,
    unit_id NUMBER NOT NULL,
    donation_date DATE DEFAULT SYSDATE,
    remarks VARCHAR2(200),

    CONSTRAINT fk_dr_donor
    FOREIGN KEY (donor_id)
    REFERENCES DONOR(donor_id),

    CONSTRAINT fk_dr_unit
    FOREIGN KEY (unit_id)
    REFERENCES BLOOD_UNIT(unit_id),

    CONSTRAINT uq_unit_once UNIQUE (unit_id)
);

CREATE TABLE BLOOD_REQUEST (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id NUMBER NOT NULL,
    blood_group VARCHAR2(5) NOT NULL,
    quantity NUMBER CHECK (quantity > 0),
    request_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20)
        CHECK (status IN ('Pending','Approved','Rejected')),

    CONSTRAINT fk_br_hospital
    FOREIGN KEY (hospital_id)
    REFERENCES HOSPITAL(hospital_id)
);

CREATE TABLE ISSUE_RECORD (
    issue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id NUMBER NOT NULL,
    hospital_id NUMBER NOT NULL,
    issue_date DATE DEFAULT SYSDATE,
    handled_by NUMBER,

    CONSTRAINT fk_ir_unit
    FOREIGN KEY (unit_id)
    REFERENCES BLOOD_UNIT(unit_id),

    CONSTRAINT fk_ir_hospital
    FOREIGN KEY (hospital_id)
    REFERENCES HOSPITAL(hospital_id),

    CONSTRAINT fk_ir_admin
    FOREIGN KEY (handled_by)
    REFERENCES USER_ADMIN(admin_id),

    CONSTRAINT uq_issue_unit UNIQUE (unit_id)
);

CREATE TABLE AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    action VARCHAR2(100),
    table_name VARCHAR2(50),
    record_id NUMBER,
    log_time DATE DEFAULT SYSDATE,

    CONSTRAINT fk_log_admin
    FOREIGN KEY (admin_id)
    REFERENCES USER_ADMIN(admin_id)
);


INSERT INTO BLOOD_BANK (bank_name, location, contact_no, email)
VALUES ('City Blood Center', 'New Delhi', '9876543210', 'citybank@gmail.com');

INSERT INTO BLOOD_BANK (bank_name, location, contact_no, email)
VALUES ('LifeCare Blood Bank', 'Noida', '9123456780', 'lifecare@gmail.com');



INSERT INTO USER_ADMIN (username, password, role)
VALUES ('admin1', 'admin123', 'Admin');

INSERT INTO USER_ADMIN (username, password, role)
VALUES ('staff1', 'staff123', 'Staff');


INSERT INTO DONOR 
(name, age, gender, blood_group, phone, email, address, last_donation_date)
VALUES
('Rahul Sharma', 25, 'Male', 'A+', '9000011111',
 'rahul@gmail.com', 'Delhi', TO_DATE('2025-08-10','YYYY-MM-DD'));

INSERT INTO DONOR 
(name, age, gender, blood_group, phone, email, address, last_donation_date)
VALUES
('Neha Verma', 28, 'Female', 'B+', '9000022222',
 'neha@gmail.com', 'Noida', TO_DATE('2025-07-15','YYYY-MM-DD'));
 
 
 INSERT INTO HOSPITAL (hospital_name, address, contact_no, email)
VALUES ('Apollo Hospital', 'Delhi', '9111111111', 'apollo@gmail.com');

INSERT INTO HOSPITAL (hospital_name, address, contact_no, email)
VALUES ('Fortis Hospital', 'Noida', '9222222222', 'fortis@gmail.com');


INSERT INTO BLOOD_UNIT
(blood_group, collection_date, expiry_date, status, bank_id)
VALUES
('A+', SYSDATE-5, SYSDATE+35, 'Available', 1);

INSERT INTO BLOOD_UNIT
(blood_group, collection_date, expiry_date, status, bank_id)
VALUES
('B+', SYSDATE-10, SYSDATE+30, 'Available', 1);


INSERT INTO DONATION_RECORD
(donor_id, unit_id, remarks)
VALUES (1, 1, 'Regular donor');

INSERT INTO DONATION_RECORD
(donor_id, unit_id, remarks)
VALUES (2, 2, 'First time donor');


COMMIT;

--View All Donors
SELECT donor_id, name, blood_group, phone
FROM DONOR;

--available blood stock
SELECT b.unit_id, b.blood_group, b.status, bb.bank_name
FROM BLOOD_UNIT b
JOIN BLOOD_BANK bb
ON b.bank_id = bb.bank_id
WHERE b.status = 'Available';


--donor donation history
SELECT d.name, dr.donation_date, b.unit_id
FROM DONOR d
JOIN DONATION_RECORD dr ON d.donor_id = dr.donor_id
JOIN BLOOD_UNIT b ON dr.unit_id = b.unit_id;


--total units of every sample
SELECT blood_group, COUNT(*) AS total_units
FROM BLOOD_UNIT
WHERE status = 'Available'
GROUP BY blood_group;


--Hospitals with Requests
SELECT hospital_name
FROM HOSPITAL
WHERE hospital_id IN
(
  SELECT hospital_id
  FROM BLOOD_REQUEST
  WHERE status = 'Pending'
);

--view
CREATE VIEW available_blood_view AS
SELECT b.unit_id, b.blood_group, bb.bank_name
FROM BLOOD_UNIT b
JOIN BLOOD_BANK bb
ON b.bank_id = bb.bank_id
WHERE b.status = 'Available';

SELECT * FROM available_blood_view;


INSERT INTO DONOR (name, age, gender, blood_group, phone, email, address, last_donation_date)
VALUES ('Amit Kumar', 32, 'Male', 'O+', '9000033333', 'amit@gmail.com', 'Delhi', SYSDATE-120);

INSERT INTO DONOR VALUES (DEFAULT,'Pooja Singh',26,'Female','A+','9000044444',
'pooja@gmail.com','Noida',SYSDATE-90);

INSERT INTO DONOR VALUES (DEFAULT,'Rohit Mehta',29,'Male','B+','9000055555',
'rohit@gmail.com','Gurgaon',SYSDATE-150);

INSERT INTO DONOR VALUES (DEFAULT,'Sneha Patel',24,'Female','AB+','9000066666',
'sneha@gmail.com','Delhi',SYSDATE-60);

INSERT INTO DONOR VALUES (DEFAULT,'Vikas Verma',35,'Male','O-','9000077777',
'vikas@gmail.com','Faridabad',SYSDATE-200);

INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'O+',SYSDATE-4,SYSDATE+36,'Available',1);
INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'A+',SYSDATE-6,SYSDATE+34,'Available',1);
INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'B+',SYSDATE-8,SYSDATE+32,'Available',2);
INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'AB+',SYSDATE-12,SYSDATE+28,'Available',2);
INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'O-',SYSDATE-20,SYSDATE+20,'Available',1);
INSERT INTO BLOOD_UNIT VALUES (DEFAULT,'A-',SYSDATE-40,SYSDATE-5,'Expired',1);

INSERT INTO HOSPITAL VALUES (DEFAULT,'Max Hospital','Gurgaon','9333333333','max@gmail.com');
INSERT INTO HOSPITAL VALUES (DEFAULT,'AIIMS','Delhi','9444444444','aiims@gmail.com');
INSERT INTO HOSPITAL VALUES (DEFAULT,'Medanta','Gurgaon','9555555555','medanta@gmail.com');


INSERT INTO BLOOD_REQUEST (hospital_id,blood_group,quantity,status)
VALUES (1,'A+',2,'Pending');

INSERT INTO BLOOD_REQUEST (hospital_id,blood_group,quantity,status)
VALUES (2,'O+',3,'Approved');


SELECT hospital_id, hospital_name FROM HOSPITAL;


SELECT donor_id, name FROM DONOR;
SELECT hospital_id, hospital_name FROM HOSPITAL;
SELECT bank_id, bank_name FROM BLOOD_BANK;
SELECT admin_id, username FROM USER_ADMIN;
SELECT unit_id, blood_group, status FROM BLOOD_UNIT;

INSERT INTO DONOR VALUES
(DEFAULT,'Karan Malhotra',27,'Male','A-','9000088888',
'karan@gmail.com','Delhi',SYSDATE-80);

INSERT INTO DONOR VALUES
(DEFAULT,'Riya Gupta',23,'Female','O+','9000099999',
'riya@gmail.com','Noida',SYSDATE-50);

INSERT INTO DONOR VALUES
(DEFAULT,'Ankit Jain',31,'Male','B-','9000012121',
'ankit@gmail.com','Ghaziabad',SYSDATE-140);

INSERT INTO DONOR VALUES
(DEFAULT,'Nisha Kapoor',34,'Female','AB-','9000013131',
'nisha@gmail.com','Delhi',SYSDATE-170);


INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'O+',SYSDATE-3,SYSDATE+37,'Available',1);

INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'A+',SYSDATE-7,SYSDATE+33,'Available',1);

INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'B+',SYSDATE-9,SYSDATE+31,'Available',2);

INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'AB+',SYSDATE-14,SYSDATE+26,'Available',2);

INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'O-',SYSDATE-25,SYSDATE+15,'Available',1);

INSERT INTO BLOOD_UNIT VALUES
(DEFAULT,'A+',SYSDATE-50,SYSDATE-10,'Expired',1);

INSERT INTO BLOOD_REQUEST
(hospital_id,blood_group,quantity,status)
VALUES (1,'O+',2,'Pending');

INSERT INTO BLOOD_REQUEST
(hospital_id,blood_group,quantity,status)
VALUES (2,'A+',3,'Approved');

INSERT INTO BLOOD_REQUEST
(hospital_id,blood_group,quantity,status)
VALUES (21,'B+',1,'Pending');

INSERT INTO BLOOD_REQUEST
(hospital_id,blood_group,quantity,status)
VALUES (22,'AB+',2,'Rejected');

INSERT INTO BLOOD_REQUEST
(hospital_id,blood_group,quantity,status)
VALUES (23,'O-',1,'Pending');


SELECT hospital_id, hospital_name
FROM HOSPITAL
ORDER BY hospital_id;


SELECT unit_id FROM BLOOD_UNIT
MINUS
SELECT unit_id FROM DONATION_RECORD;

--procedure to show available blood
CREATE OR REPLACE PROCEDURE show_available_blood
AS
   v_count NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_count
   FROM BLOOD_UNIT
   WHERE status = 'Available';

   DBMS_OUTPUT.PUT_LINE('Available Units: ' || v_count);
END;
/


SET SERVEROUTPUT ON;


BEGIN
   show_available_blood;
END;
/

CREATE OR REPLACE PROCEDURE register_donor (
    p_name    IN VARCHAR2,
    p_age     IN NUMBER,
    p_gender  IN VARCHAR2,
    p_group   IN VARCHAR2,
    p_phone   IN VARCHAR2,
    p_email   IN VARCHAR2,
    p_address IN VARCHAR2
)
AS
BEGIN
    -- Check age
    IF p_age < 18 OR p_age > 65 THEN
        DBMS_OUTPUT.PUT_LINE('Age must be between 18 and 65');
        RETURN;
    END IF;

    -- Insert donor
    INSERT INTO DONOR
    (name, age, gender, blood_group, phone, email, address, last_donation_date)
    VALUES
    (p_name, p_age, p_gender, p_group, p_phone, p_email, p_address, SYSDATE);

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Donor registered successfully');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Phone number already exists');

    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error occurred while registering donor');
END;
/
SET SERVEROUTPUT ON

BEGIN
   register_donor(
      'Rahul Verma',
      24,
      'Male',
      'O+',
      '9000019999',
      'rahulv@gmail.com',
      'Delhi'
   );
END;
/

SELECT name, blood_group, phone
FROM DONOR
WHERE phone='9000019999';

CREATE OR REPLACE PROCEDURE issue_blood (
    p_unit_id     IN NUMBER,
    p_hospital_id IN NUMBER,
    p_admin_id    IN NUMBER
)
AS
    v_status BLOOD_UNIT.status%TYPE;
BEGIN
    -- Get current status of blood unit
    SELECT status
    INTO v_status
    FROM BLOOD_UNIT
    WHERE unit_id = p_unit_id;

    -- Check if unit is available
    IF v_status != 'Available' THEN
        DBMS_OUTPUT.PUT_LINE('Blood unit is not available');
        RETURN;
    END IF;

    -- Insert into issue record
    INSERT INTO ISSUE_RECORD
    (unit_id, hospital_id, handled_by)
    VALUES
    (p_unit_id, p_hospital_id, p_admin_id);

    -- Update blood unit status
    UPDATE BLOOD_UNIT
    SET status = 'Issued'
    WHERE unit_id = p_unit_id;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Blood issued successfully');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Invalid Unit ID');

    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('This unit is already issued');

    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error while issuing blood');
END;
/
BEGIN
   issue_blood(1, 21, 1);
END;
/

SELECT unit_id, status FROM BLOOD_UNIT WHERE unit_id=1;

SELECT * FROM ISSUE_RECORD WHERE unit_id=1;

CREATE OR REPLACE PROCEDURE approve_request (
    p_request_id IN NUMBER
)
AS
    v_status BLOOD_REQUEST.status%TYPE;
BEGIN
    -- Get current request status
    SELECT status
    INTO v_status
    FROM BLOOD_REQUEST
    WHERE request_id = p_request_id;

    -- Only pending requests can be approved
    IF v_status != 'Pending' THEN
        DBMS_OUTPUT.PUT_LINE('Request is not pending');
        RETURN;
    END IF;

    -- Approve request
    UPDATE BLOOD_REQUEST
    SET status = 'Approved'
    WHERE request_id = p_request_id;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Request approved successfully');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Invalid Request ID');

    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error while approving request');
END;
/

SELECT request_id, status FROM BLOOD_REQUEST;

BEGIN
   approve_request(1);
END;
/

CREATE OR REPLACE TRIGGER trg_log_issue
AFTER INSERT ON ISSUE_RECORD
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG
    (admin_id, action, table_name, record_id)
    VALUES
    (:NEW.handled_by,
     'Issued Blood Unit',
     'ISSUE_RECORD',
     :NEW.issue_id);
END;
/

BEGIN
   issue_blood(2, 1, 1);
END;
/

SELECT * FROM AUDIT_LOG;

CREATE OR REPLACE TRIGGER trg_check_expiry
BEFORE INSERT OR UPDATE ON BLOOD_UNIT
FOR EACH ROW
BEGIN
    IF :NEW.expiry_date < SYSDATE THEN
        :NEW.status := 'Expired';
    END IF;
END;
/

SELECT trigger_name, status
FROM user_triggers
WHERE table_name = 'BLOOD_UNIT';

INSERT INTO BLOOD_UNIT
VALUES (DEFAULT,'AB-',SYSDATE-30,SYSDATE-2,'Available',1);

SELECT unit_id, status
FROM BLOOD_UNIT
ORDER BY unit_id DESC;



CREATE OR REPLACE FUNCTION check_stock (
    p_group IN VARCHAR2
)
RETURN NUMBER
AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM BLOOD_UNIT
    WHERE blood_group = p_group
    AND status = 'Available';

    RETURN v_count;
END;
/
SELECT check_stock('A+') FROM DUAL;
SELECT check_stock('O+') FROM DUAL;


CREATE OR REPLACE PROCEDURE donor_report
AS
    CURSOR c_donor IS
        SELECT name, blood_group, phone
        FROM DONOR;

    v_name  DONOR.name%TYPE;
    v_group DONOR.blood_group%TYPE;
    v_phone DONOR.phone%TYPE;

BEGIN
    OPEN c_donor;

    LOOP
        FETCH c_donor INTO v_name, v_group, v_phone;
        EXIT WHEN c_donor%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
          v_name || ' | ' || v_group || ' | ' || v_phone
        );
    END LOOP;

    CLOSE c_donor;
END;
/
SET SERVEROUTPUT ON

BEGIN
   donor_report;
END;
/









































